root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/core-event ./cmd/"
bin = "tmp/core-event"
full_bin = "USER=postgres ENV_FILE=./.env.dev ./tmp/core-event"
include_ext = ["go", "yaml"]
exclude_dir = ["tmp"]
kill_delay = "1s"
