syntax = "proto3";

package core.v1;

import "request/v1/base.proto";
import "api/v1/generators.proto";
import "api/v1/permissions.proto";
import "buf/validate/validate.proto";
import "google/protobuf/empty.proto";

option go_package = "app/core/gen/core/v1;corev1";

service AbsenceService {
  option (api.v1.permissionKey) = "Absence";

  rpc Autocomplete(request.v1.AutocompleteRequest) returns (request.v1.AutocompleteResponse);
  rpc Create(SaveAbsenceRequest) returns (Absence) {}
  rpc Get(request.v1.GetRequest) returns (Absence) {}
  rpc List(request.v1.SelectRequest) returns (ListAbsenceResponse) {}
  rpc Update(SaveAbsenceRequest) returns (Absence) {}
  rpc SoftDelete(request.v1.DeleteRequest) returns (request.v1.DeleteResponse);
  rpc Delete(request.v1.DeleteRequest) returns (request.v1.DeleteResponse);
}

message Absence {
  option (api.v1.ts_grid) = true;

  string id = 1[(api.v1.ts_grid_opts) = {
    column: {
      visible: false,
    }
  }];
  optional string therapistId = 2[(api.v1.ts_grid_opts) = {
    column: {
      visible: false
    },
    filter: {
      form: true,
      formLabel: "Therapist",
    }
  }];
  optional string therapistLabel = 3;
  optional string therapistAbbreviationLabel = 8;
  int64 fromTime = 4[(api.v1.ts_grid_opts) = {
    column: {
      header: "From"
    }
  }];
  int64 tillTime = 5[(api.v1.ts_grid_opts) = {
    column: {
      header: "Till"
    }
  }];
  optional string reason = 6;

  int64 createdAt = 100;
  string createdBy = 101;
  optional string createdByLabel = 102;
  optional int64 updatedAt = 103;
  optional string updatedBy = 104;
  optional string updatedByLabel = 105;
  optional int64 deletedAt = 106;
  optional string deletedBy = 107;
  optional string deletedByLabel = 108;
}

message SaveAbsenceRequest {
  string id = 1;
  optional string therapistId = 2;
  int64 fromTime = 4[(buf.validate.field).int64.gt = 0];
  int64 tillTime = 5[(buf.validate.field).int64.gt = 0];
  optional string reason = 6;
}

message ListAbsenceResponse {
  repeated Absence items = 1;
  request.v1.PaginationResponse pagination = 2;
}
