syntax = "proto3";

package core.v1;

import "request/v1/base.proto";
import "api/v1/generators.proto";
import "api/v1/permissions.proto";
import "buf/validate/validate.proto";

option go_package = "app/core/gen/core/v1;corev1";

service CountryService {
  option (api.v1.permissionKey) = "Country";

  rpc Autocomplete(request.v1.AutocompleteRequest) returns (request.v1.AutocompleteResponse);
  rpc NationalityAutocomplete(request.v1.AutocompleteRequest) returns (request.v1.AutocompleteResponse);
  rpc Get(request.v1.GetRequest) returns (Country);
  rpc List(request.v1.SelectRequest) returns (ListCountryResponse);
  rpc Create(SaveCountryRequest) returns (Country);
  rpc Update(SaveCountryRequest) returns (Country);
  rpc SoftDelete(request.v1.DeleteRequest) returns (request.v1.DeleteResponse);
  rpc Delete(request.v1.DeleteRequest) returns (request.v1.DeleteResponse);
}

message Country {
  option (api.v1.ts_grid) = true;

  string id = 1;
  string iso2 = 2;
  string iso3 = 3;
  string name = 4;
  string nationalityName = 5;
  optional string timezone = 6;

  int64 createdAt = 100;
  string createdBy = 101;
  string createdByLabel = 102;
  optional int64 updatedAt = 103;
  optional string updatedBy = 104;
  optional string updatedByLabel = 105;
  optional int64 deletedAt = 106;
  optional string deletedBy = 107;
  optional string deletedByLabel = 108;
}

message ListCountryResponse {
  repeated Country items = 1;
  request.v1.PaginationResponse pagination = 2;
}

message SaveCountryRequest {
  string id = 1;
  string iso2 = 2 [
    (buf.validate.field) = {required: true},
    (buf.validate.field).cel = {
      id: "SaveCountryRequest.iso2"
      message: "ISO2 must be set"
      expression: "this != ''"
    }
  ];
  string iso3 = 3 [
    (buf.validate.field) = {required: true},
    (buf.validate.field).cel = {
      id: "SaveCountryRequest.iso3"
      message: "ISO3 must be set"
      expression: "this != ''"
    }
  ];
  string name = 4 [
    (buf.validate.field) = {required: true},
    (buf.validate.field).cel = {
      id: "SaveCountryRequest.name"
      message: "Name must be set"
      expression: "this != ''"
    }
  ];
  string nationalityName = 5 [
    (buf.validate.field) = {required: true},
    (buf.validate.field).cel = {
      id: "SaveCountryRequest.nationalityName"
      message: "Nationality name must be set"
      expression: "this != ''"
    }
  ];
  optional string timezone = 6;
}
