syntax = "proto3";

package core.v1;

import "request/v1/base.proto";
import "api/v1/generators.proto";
import "api/v1/permissions.proto";
import "buf/validate/validate.proto";
import "google/protobuf/empty.proto";

option go_package = "app/core/gen/core/v1;corev1";

service TransactionService {
  option (api.v1.permissionKey) = "Transaction";

  rpc Autocomplete(request.v1.AutocompleteRequest) returns (request.v1.AutocompleteResponse);
  rpc Create(SaveTransactionRequest) returns (Transaction) {}
  rpc Get(request.v1.GetRequest) returns (Transaction) {}
  rpc List(request.v1.SelectRequest) returns (ListTransactionResponse) {}
  rpc Update(SaveTransactionRequest) returns (Transaction) {}
  rpc SoftDelete(request.v1.DeleteRequest) returns (request.v1.DeleteResponse);
  rpc Delete(request.v1.DeleteRequest) returns (request.v1.DeleteResponse);
}

message Transaction {
  option (api.v1.ts_grid) = true;

  string id = 1[(api.v1.ts_grid_opts) = {
    column: {
      visible: false,
    }
  }];
  optional string recurringCashflowId = 2[(api.v1.ts_grid_opts) = {
    column: {
      visible: false,
    },
    filter: {
      form: true,
      formLabel: "Recurring Cashflow",
    }
  }];
  optional string recurringCashflowLabel = 3[(api.v1.ts_grid_opts) = {
    column: {
      header: "Recurring Cashflow",
      visible: true,
    }
  }];
  string displayName = 4[(api.v1.ts_grid_opts) = {
    column: {
      header: "Name",
      visible: true,
    },
    filter: {
      quick: true,
    }
  }];
  string amount = 5[(api.v1.ts_grid_opts) = {
    column: {
      header: "Amount",
      visible: true,
    }
  }];
  int64 incurredAt = 6[(api.v1.ts_grid_opts) = {
    column: {
      header: "Incurred At",
      visible: true,
    }
  }];

  int64 createdAt = 100;
  string createdBy = 101;
  optional string createdByLabel = 102;
  optional int64 updatedAt = 103;
  optional string updatedBy = 104;
  optional string updatedByLabel = 105;
  optional int64 deletedAt = 106;
  optional string deletedBy = 107;
  optional string deletedByLabel = 108;
}

message SaveTransactionRequest {
  string id = 1;
  optional string recurringCashflowId = 2;
  string displayName = 3[(buf.validate.field).string.min_len = 1];
  string amount = 4[(buf.validate.field).string.min_len = 1];
  int64 incurredAt = 5[(buf.validate.field).int64.gt = 0];
}

message ListTransactionResponse {
  repeated Transaction items = 1;
  request.v1.PaginationResponse pagination = 2;
}
