import {createEcmaScriptPlugin, runNodeJs} from "@bufbuild/protoplugin";
import {type Schema} from "@bufbuild/protoplugin/ecmascript";
import {DescMethod, DescService, getExtension, hasExtension} from "@bufbuild/protobuf";
import {permissionAbility, permissionKey, hideAbility} from "../gen/api/v1/permissions_pb";
import {fileIgnored} from "./utils";
import { capitalCase } from 'change-case';

const protoGenTSEnums = createEcmaScriptPlugin({
  name: "permission-plugin",
  version: `v1.0.0`,
  generateTs,
});

function generateTs(schema: Schema) {

  const f = schema.generateFile("ability-autocomplete.ts");

  console.error("Created ability-autocomplete.ts")
  f.print(`// generated by ability-autocomplete-plugin`)
  f.print(`// DO NOT EDIT`)

  f.print("import { IAutocompleteItem } from '@gen/interface';")

  f.print(`export const AbilityAutocompleteItems = {`)

  const permissionMap = {};

  const renderService = (s: DescService) => {
    const key = getPermissionKey(s);
    if (key == "") return;

    for (const m of s.methods) {
      let ability = getPermissionAbility(m);
      if (ability == "") {
        ability = m.name;
      }
      else {
        continue;
      }

      // Add the ability to the permission map
      if (!permissionMap[key]) {
        permissionMap[key] = [];
      }

      permissionMap[key].push({
        ID: ability,
        label: capitalCase(ability),
      });
    }
  };

  for (const file of schema.files) {
    if (["buf/validate/"].some(prefix => file.name.startsWith(prefix))) continue;

    if (fileIgnored(file)) continue;

    for (const s of file.services) {
      renderService(s);
    }
  }

  // Print the permission map in the correct format
  Object.keys(permissionMap).forEach(permissionKey => {
    f.print(`  "${permissionKey}": [`);
    permissionMap[permissionKey].forEach(item => {
      f.print(`    ${JSON.stringify(item)},`);
    });
    f.print(`  ],`);
  });

  f.print(`} as Record<string, IAutocompleteItem[]>;`);
}

function getPermissionKey(s: DescService) {
  if (s.proto.options && hasExtension(s.proto.options, permissionKey)) {
    return getExtension(s.proto.options, permissionKey);
  }
  return "";
}

function getPermissionAbility(m: DescMethod) {
  if (m.proto.options && hasExtension(m.proto.options, hideAbility)) {
    return getExtension(m.proto.options, hideAbility);
  }
  return "";
}

runNodeJs(protoGenTSEnums);
