import { createEcmaScriptPlugin, runNodeJs } from '@bufbuild/protoplugin';
import { type Schema } from '@bufbuild/protoplugin/ecmascript';
import { DescEnum, DescEnumValue, getExtension, hasExtension } from '@bufbuild/protobuf';
import { ts_enum_desc, ts_enum_ignore  } from '../gen/api/v1/generators_pb';

const protoGenTSEnums = createEcmaScriptPlugin({
  name: "enum-plugin",
  version: `v1.0.0`,
  generateTs,
});

function generateTs(schema: Schema) {
  const f = schema.generateFile("enums.ts");
  const enums: string[] = []
  f.print(`// generated by enum-plugin`)
  for (const file of schema.files) {
    // console.error(`Processing file: ${file.name} with ${file.enums.length} enums`)

    let before = "";
    let prefix = "";

    for (const e of file.enums) {
      // check if it's ignored
      if (e.proto.options && hasExtension(e.proto.options, ts_enum_ignore)) {
        const ignoreValue = getExtension(e.proto.options, ts_enum_ignore)
        if (ignoreValue === true) {
          continue;
        }
      }

      const vals: Map<string, string> = new Map<string, string>();
      for (const v of e.values) {
        if (vals.has(String(v.number)) || v.number < 0) {
          continue;
        }

        const desc = getDescription(v)
        if (desc === "") {
          continue;
        }

        vals.set(String(v.number), desc)
      }

      // if there are no values, then skip this enum
      if (vals.size === 0) {
        continue;
      }

      let name = getName(file.proto.package, e);
      if (prefix !== "" && before !== "") {
        name = prependPrefix(name, before, prefix);
      }

      enums.push(name)

      f.print(`// @generated from enum: ${e.typeName}`)
      f.print(`const ${name} = {`)

      f.print(`  ${Array.from(vals).map(([k, v]) => `${k}: "${v}"`).join(",\n  ")}`)
      f.print(`}`)

      // print blank line
      f.print("")
    }
  }

  f.print(`export const enums = { ${enums.join(", ")} }`)
  f.print(`export type enumKeys = keyof typeof enums;`)

  console.error("Created enums.ts")
}

function getName(pkg: string, e: DescEnum): string {
  // if (e.proto.options && hasExtension(e.proto.options, ts_enum_name)) {
  //   return getExtension(e.proto.options, ts_enum_name)
  // }

  let name = e.name

  // if pkg starts with app. / lib. but is not app.shared then
  // prefix name with parts of package between app and the penultimate part
  // prefix should be camel case and start with capital letter
  if (pkg.startsWith("app.") || pkg.startsWith("lib.")) {
    const parts = pkg.split(".");
    if (parts.length > 2) {
      if (parts[1] !== "shared") {
        name = parts.slice(1, -1).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("") + name.charAt(0).toUpperCase() + name.slice(1)
      }
    }
  }

  return name
}

function getDescription(e: DescEnumValue): string {
  if (e.proto.options && hasExtension(e.proto.options, ts_enum_desc)) {
    return getExtension(e.proto.options, ts_enum_desc)
  }
  return ""
}

function prependPrefix(v, before, prefix) {
  // Find the index of the first instance of 'before'
  const index = v.indexOf(before);

  // If 'before' is not found, return the original string
  if (index === -1) {
    return v;
  }

  // Create the new string with the prefix prepended to the first instance of 'before'
  return v.slice(0, index) + prefix + v.slice(index);
}

runNodeJs(protoGenTSEnums);
