import { createEcmaScriptPlugin, runNodeJs } from "@bufbuild/protoplugin";
import { type Schema } from "@bufbuild/protoplugin/ecmascript";
import {DescEnum, DescField, DescMessage} from "@bufbuild/protobuf";
import { fileIgnored, messageName, } from './utils';


const protoGenTSEnums = createEcmaScriptPlugin({
    name: "factory-plugin",
    version: `v1.0.0`,
    generateTs,
});

function generateTs(schema: Schema) {

    const f = schema.generateFile("factory.ts");
    const debug = false;

    console.error("Created factory.ts")
    f.print(`// generated by factory-plugin`)

    const renderMessage = (m: DescMessage) => {
        if(debug) f.print(`// @generated from message ${m.typeName}`)
        const name = messageName(m)

        const msgImport = f.import(m)
        const ifImport = f.import(`I${name}`, `./interface`)
        const msgName = messageName(m)


        f.print(`   // ${m.file.name} ${m.typeName}`)
        f.print(`   "${msgName}": {`)
        f.print(`       class: `, msgImport, `,`)
        f.print(`       interface: {} as `, ifImport, `,`)
        f.print(`   },`)

        for(const nm of m.nestedMessages ) {
            renderMessage(nm)
        }

    }

    f.print(`export const messages = {`)
        for (const file of schema.files) {
            if ([
                "buf/validate/"
            ].some(prefix => file.name.startsWith(prefix))) continue;

            // check if the file is ignored
            if (fileIgnored(file)) {
                continue;
            }

            for ( const m of file.messages) {
                renderMessage(m)
            }

        }
    f.print(`}`)

}


runNodeJs(protoGenTSEnums);
