import {createEcmaScriptPlugin, runNodeJs} from "@bufbuild/protoplugin";
import {type Schema} from "@bufbuild/protoplugin/ecmascript";
import {DescField, DescMessage, getExtension, hasExtension} from "@bufbuild/protobuf";
import {fileIgnored, interfaceName, resolveScalarType} from "./utils";
import {ts_grid, ts_grid_name, ts_grid_opts, TsGridOptions,} from "../gen/api/v1/generators_pb";
import {capitalCase} from 'change-case';

let builders: GridBuilder[] = [];

const defaultExcludedFilters = {
  "id": true,
}

const defaultInvisibleFields = {
  "id": true,
  "createdAt": true,
  "createdBy": true,
  "createdByLabel": true,
  "deletedAt": true,
  "deletedBy": true,
  "deletedByLabel": true,
  "updatedAt": true,
  "updatedBy": true,
  "updatedByLabel": true,
}

const defaultHeaders = {
  createdAt: "Created At",
  createdBy: "Created By Id",
  createdByLabel: "Created By",
  updatedAt: "Updated At",
  updatedBy: "Updated By Id",
  updatedByLabel: "Updated By",
  deletedAt: "Deleted At",
  deletedBy: "Deleted By Id",
  deletedByLabel: "Deleted By",
};

type Grid = {
  name: string;
  columns: GridColumn[];
  filters: GridFilter[];
}

type GridFilter = {
  id: string;
  enum: boolean;
  form: boolean;
  formLabel?: string;
  quick: boolean;
  quickLabel?: string;
  type: string;
}

type GridColumn = {
  id: string;
  enum: boolean;
  header: string;
  type: string;
  visible: boolean;
  columnRendererType?: string;
  enableSorting?: boolean;
  filterField?: string;
};

class GridBuilder {
  private name: string = "";
  private columns: GridColumn[] = [];
  private filters: GridFilter[] = [];

  getName(): string {
    return this.name;
  }

  setName(name: string) {
    this.name = name;
  }

  setColumns(columns: GridColumn[]): void {
    this.columns = columns;
  }

  setFilters(filters: GridFilter[]): void {
    this.filters = filters;
  }

  toString(): string {
    let result = `export const ${this.name}Grid: Grid = {\n`;
    result += `  name: "${this.name}",\n`;

    result += `  columns: [\n`;
    for (const column of this.columns) {
      result += `    {\n`;
      result += `      id: "${column.id}",\n`;
      result += `      enum: ${column.enum},\n`;
      result += `      header: "${column.header}",\n`;
      result += `      type: "${column.type}",\n`;
      result += `      visible: ${column.visible},\n`;
      if (column?.columnRendererType) {
        result += `      columnRendererType: "${column.columnRendererType}",\n`;
      }
      if (column?.enableSorting !== undefined) {
        result += `      enableSorting: ${column.enableSorting},\n`;
      }
      if (column?.filterField) {
        result += `      filterField: "${column.filterField}",\n`;
      }
      result += `    },\n`;
    }
    result += `  ],\n`;

    result += `  filters: [\n`;
    for (const filter of this.filters) {
      result += `    {\n`;
      result += `      id: "${filter.id}",\n`;
      result += `      enum: ${filter.enum},\n`;
      result += `      form: ${filter.form},\n`;

      if (filter.formLabel) {
        result += `      formLabel: "${filter.formLabel}",\n`;
      }

      result += `      quick: ${filter.quick},\n`;

      if (filter.quickLabel) {
        result += `      quickLabel: "${filter.quickLabel}",\n`;
      }

      result += `      type: "${filter.type}"\n`;
      result += `    },\n`;
    }
    result += `  ]\n`;

    result += `};\n`;

    return result;
  }
}

const protoGenTSEnums = createEcmaScriptPlugin({
  name: "grid-plugin",
  version: `v1.0.0`,
  generateTs,
});

function generateTs(schema: Schema) {

  const f = schema.generateFile("grids.ts");

  console.error("Created grids.ts")
  f.print(`// generated by grid-plugin`)
  f.print(`// DO NOT EDIT`)

  f.print("")
  f.print(`export type Grid = {`)
  f.print(`  name: string;`)
  f.print(`  columns: GridColumn[];`)
  f.print(`  filters: GridFilter[];`)
  f.print(`}`)

  f.print("")
  f.print(`export type GridColumn = {`)
  f.print(`  id: string;`)
  f.print(`  enum: boolean;`)
  f.print(`  header: string;`)
  f.print(`  type: string;`)
  f.print(`  visible: boolean;`)
  f.print(`  columnRendererType?: string;`)
  f.print(`  enableSorting?: boolean;`)
  f.print(`  filterField?: string;`)
  f.print(`};`)

  f.print("")
  f.print(`export type GridFilter = {`)
  f.print(`  id: string;`)
  f.print(`  enum: boolean;`)
  f.print(`  form: boolean;`)
  f.print(`  formLabel?: string;`)
  f.print(`  quick: boolean;`)
  f.print(`  quickLabel?: string;`)
  f.print(`  type: string;`)
  f.print(`  quickWidthPx?: number;`)
  f.print(`  modalXs?: number;`)
  f.print(`};`)

  f.print("")

  const renderGrid = (m: DescMessage) => {
    const gb = new GridBuilder();

    let gridName = getGridName(m)
    if (!gridName) {
      gridName = m.name
    }
    gb.setName(gridName);

    const fieldNames = new Set(m.fields.map(fd => fd.name))

    type Indexed = { col: GridColumn; sortKey: number }
    const indexedColumns: Indexed[] = []
    let filters: GridFilter[] = []

    m.fields.forEach((f, declaredIndex) => {
      const opts = getGridOpts(f)

      const isEnum = fieldIsEnum(f)
      const fieldType = getFieldType(f)

      // `column.exclude` skips the column only — the field can still have
      // a filter (e.g. a foreign-key id that has no column representation
      // but is exposed as an autocomplete filter).
      if (!opts?.column?.exclude) {
        let visible = true;
        if (defaultInvisibleFields[f.name] && opts?.column?.visible !== true) {
          visible = false;
        }
        if (opts?.column?.visible === false) {
          visible = false;
        }

        const col: GridColumn = {
          id: f.name,
          enum: isEnum,
          header: getColumnHeader(f, opts),
          visible: visible,
          type: fieldType,
          columnRendererType: opts?.column?.columnRendererType,
          enableSorting: opts?.column?.enableSorting,
          filterField: resolveFilterField(f.name, opts, fieldNames),
        }

        const sortKey = opts?.column?.order ?? declaredIndex
        indexedColumns.push({ col, sortKey })
      }

      const filter: GridFilter = {
        id: f.name,
        enum: isEnum,
        form: opts?.filter?.form !== false,
        quick: !!opts?.filter?.quick,
        type: opts?.filter?.type || fieldType
      }

      if (opts?.filter?.formLabel) {
        filter.formLabel = opts?.filter?.formLabel
      }

      if (opts?.filter?.quickLabel) {
        filter.quickLabel = opts?.filter?.quickLabel
      }
      if (!(filter.id in defaultExcludedFilters)) {
        filters.push(filter)
      }
    })

    indexedColumns.sort((a, b) => a.sortKey - b.sortKey)
    const columns = indexedColumns.map((x) => x.col)

    gb.setColumns(columns)
    gb.setFilters(filters)

    builders.push(gb)
  }

  for (const file of schema.files) {
    if ([
      "buf/validate/"
    ].some(prefix => file.name.startsWith(prefix))) continue;

    // check if the file is ignored
    if (fileIgnored(file)) {
      continue;
    }

    for (const m of file.messages) {
      if (isGrid(m)) {
        renderGrid(m)
      }
    }
  }

  builders.sort((a, b) => a.getName().localeCompare(b.getName()))

  for (const gb of builders) {
    f.print(gb.toString())
  }
}

function isGrid(m: DescMessage) {
  if (m.proto.options && hasExtension(m.proto.options, ts_grid)) {
    return getExtension(m.proto.options, ts_grid)
  }
  return false
}

function getGridName(m: DescMessage): string | undefined {
  if (m.proto.options && hasExtension(m.proto.options, ts_grid_name)) {
    return getExtension(m.proto.options, ts_grid_name)
  }
  return undefined
}

function getColumnHeader(f: DescField, opts?: TsGridOptions) {
  if (opts) {
    if (opts.column?.header) {
      return opts.column.header
    }
  }

  if (f.name in defaultHeaders) {
    return defaultHeaders[f.name]
  }

  let header = f.name.replace(/([a-z0-9])([A-Z])/g, '$1 $2');

  header = header.split(' ').map(word => {
    return /^[A-Z]+$/.test(word) ? word : capitalCase(word);
  }).join(' ');

  if (header.endsWith(" Name")) {
    header = header.slice(0, -5);
  }

  if (header.endsWith(" Label")) {
    header = header.slice(0, -6);
  }

  if (header.endsWith(" Id")) {
    header = header.slice(0, -' Id'.length).trim();
  }

  return header;
}

function resolveFilterField(name: string, opts: TsGridOptions | undefined, fieldNames: Set<string>): string | undefined {
  if (opts?.column?.filterTarget) {
    return opts.column.filterTarget
  }
  if (name.endsWith("Label")) {
    const sibling = name.slice(0, -"Label".length) + "Id"
    if (fieldNames.has(sibling)) {
      return sibling
    }
    return undefined
  }
  return name
}

function getGridOpts(f: DescField) {
  if (f.proto.options && hasExtension(f.proto.options, ts_grid_opts)) {
    return getExtension(f.proto.options, ts_grid_opts)
  }
  return undefined
}

function fieldIsEnum(f: DescField) {
  return f.fieldKind === "enum";
}

function getFieldType(f: DescField) {
  let tsType = "unknown"
  let optional = ""
  let repeated = ""

  if (f.optional) {
    optional = "?"
  }

  if (f.repeated) {
    repeated = "[]"
  }

  switch (f.fieldKind) {

    case "scalar":
      const scalarType = f.scalar
      tsType = resolveScalarType(scalarType) || 'any';
      return `${tsType}${repeated}`

    case "message":
      tsType = interfaceName(f.message!)
      return `${tsType}${repeated}`

    case "enum":
      return `${f.enum.name}${repeated}`

    default:
      return `any${repeated}`
  }
}

runNodeJs(protoGenTSEnums);
