import {createEcmaScriptPlugin, runNodeJs} from "@bufbuild/protoplugin";
import {type Schema} from "@bufbuild/protoplugin/ecmascript";
import {DescField, DescMessage} from "@bufbuild/protobuf";
import { fileIgnored, interfaceName, resolveScalarType } from './utils';
import {Printable} from "@bufbuild/protoplugin/dist/cjs/ecmascript/generated-file";

const protoGenTSEnums = createEcmaScriptPlugin({
  name: "interface-plugin",
  version: `v1.0.0`,
  generateTs,
});

function generateTs(schema: Schema) {

  const f = schema.generateFile("interface.ts");
  const debug = false;

  console.error("Created interface.ts")
  f.print(`// generated by interface-plugin`)

  /**
   *  Generates an array of string|Printables to be passed to f.print()
   *  Should always return an array of three elements
   *  1: the field name + optional quantifier + colon
   *  2: the type as a string or Printable import reference
   *  3: the repeated quantifier
   *
   *  this is used elsewhere in the code when only parts of the field spec are needed, see oneOfs
   */
  const generateField = (field: DescField): (string | Printable)[] => {

    let tsType = "unknown"
    let optional = ""
    let repeated = ""

    if (field.optional) {
      optional = "?"
    }

    if (field.repeated) {
      repeated = "[]"
    }

    switch (field.fieldKind) {

      case "scalar":

        const scalarType = field.scalar
        tsType = resolveScalarType(scalarType) || 'any';
        return [`${field.name}${optional}: `, tsType, repeated]

      case "message":

        // we can import these types from @bufbuild/protobuf
        if (field.message!.typeName!.startsWith("google.protobuf.")) {
          tsType = field.message!.name
          let imp = f.import(tsType, "@bufbuild/protobuf")
          return [`${field.name}${optional}: `, imp, repeated]
        }
        // otherwise reference to an interface we're generating
        else {
          tsType = interfaceName(field.message!)
          return [`${field.name}${optional}: `, tsType, repeated]
        }

      case "enum":
        const importFrom = field.enum?.file.name
        if (importFrom) {
          let imp = f.import(field.enum!)
          return [`${field.name}${optional}: `, imp, repeated]
        }
        break;

      default:
        return [`${field.name}${optional}: `, `any`, repeated]
    }
    return []
  }


  const renderMessage = (m: DescMessage) => {

    if (debug) f.print(`// @generated from message ${m.typeName}`)
    f.print(`export interface ${interfaceName(m)} {`)

    m.oneofs.forEach(oneof => {
      f.print(`   // @generated from oneOf: ${oneof.name}`)
      f.print(`   ${oneof.name}: `)
      oneof.fields.map(off => {

        f.print(`   {
        case: "${off.name}"
        value: `, generateField(off).slice(1), `
    } | `)
      })
      f.print(`   { case: undefined; value?: undefined }`)

    })


    for (const field of m.fields) {
      // we'll deal with oneOfs separately
      if (field.oneof) continue

      if (debug) f.print(`    // @generated from field: ${field.declarationString()}`)
      f.print("   ", ...generateField(field))

    }

    f.print(`}`)

    for (const nm of m.nestedMessages) {
      renderMessage(nm)
    }

  }

  for (const file of schema.files) {
    if ([
      "buf/validate/"
    ].some(prefix => file.name.startsWith(prefix))) continue;

    // check if the file is ignored
    if (fileIgnored(file)) {
      continue;
    }


    for (const m of file.messages) {
      renderMessage(m)
    }
  }
}

runNodeJs(protoGenTSEnums);
