import {createEcmaScriptPlugin, runNodeJs} from "@bufbuild/protoplugin";
import {type Schema} from "@bufbuild/protoplugin/ecmascript";
import {DescMethod, DescService, getExtension, hasExtension} from "@bufbuild/protobuf";
import {permissionAbility, permissionAllowAll, permissionKey} from "../gen/api/v1/permissions_pb";
import {fileIgnored} from "./utils";

type Permission = {
  Key: string;
  Open: string[];
  Restricted: string[];
};

class PermissionsBuilder {
  private perms: { [name: string]: Permission } = {};

  // Check if a group exists
  exists(name: string): boolean {
    return !!this.perms[name];
  }

  addPermission(name: string): void {
    if (!this.perms[name]) {
      this.perms[name] = {Key: name, Open: [], Restricted: []};
    }
  }

  // Set the 'Open' permissions for a group
  setOpen(name: string, permissions: string[]): void {
    this.addPermission(name);
    this.perms[name].Open = permissions;
  }

  // Set the 'Restricted' permissions for a group
  setRestricted(name: string, permissions: string[]): void {
    this.addPermission(name);
    this.perms[name].Restricted = permissions;
  }

  // Convert the groups to a string, sorted alphabetically by group name
  toString(): string {
    const sortedGroupNames = Object.keys(this.perms).sort();

    // Proper TypeScript type for the output
    let result = `export const Permissions = {\n`;

    // Loop through each group and add it to the string
    sortedGroupNames.forEach((group) => {
      const groupData = this.perms[group];
      result += `  ${group}: {\n`;
      result += `    "Key": "${groupData.Key}",\n`;
      result += `    "Open": ${JSON.stringify(groupData.Open)},\n`;
      result += `    "Restricted": ${JSON.stringify(groupData.Restricted)},\n`;
      result += `  },\n`;
    });

    // Remove the last comma and newline
    if (result.endsWith(',\n')) {
      result = result.slice(0, -2);
    }

    // Close the object
    result += `\n};`;

    return result;
  }
}

const protoGenTSEnums = createEcmaScriptPlugin({
  name: "permission-plugin",
  version: `v1.0.0`,
  generateTs,
});

function generateTs(schema: Schema) {

  const f = schema.generateFile("permissions.ts");

  console.error("Created permissions.ts")
  f.print(`// generated by permissions-plugin`)
  f.print(`// DO NOT EDIT`)

  f.print("")

  f.print(`export type Permission = {
  Key: string
  Open: string[];
  Restricted: string[];
};`)

  const pb = new PermissionsBuilder();

  const renderService = (s: DescService) => {
    // check if the service has a api.v1.permissionGroup extension

    const key = getPermissionKey(s)
    if (key == "") {
      return
    }

    if (pb.exists(key)) {
      return
    }

    pb.addPermission(key)

    let open: string[] = []
    let restricted: string[] = []

    for (const m of s.methods) {
      let ability = getPermissionAbility(m)
      if (ability == "") {
        ability = m.name
      }

      // check if it
      let allowAll = getPermissionAllowAll(m)

      if (allowAll) {
        // check if it is already in the open array
        if (!open.includes(ability)) {
          open.push(ability)
        }
      }

      // if name = Autocomplete, Get, ListView then it = Read
      if (["Autocomplete", "Get", "ListView"].includes(m.name)) {
        ability = "Read"
      }

      // check if it is already in the restricted array
      if (!restricted.includes(ability)) {
        restricted.push(ability)
      }
    }

    pb.setOpen(key, open)
    pb.setRestricted(key, restricted)
  }

  for (const file of schema.files) {
    if ([
      "buf/validate/"
    ].some(prefix => file.name.startsWith(prefix))) continue;

    // check if the file is ignored
    if (fileIgnored(file)) {
      continue;
    }

    for (const s of file.services) {
      renderService(s)
    }
  }


  f.print("")
  f.print(pb.toString())
}

function getPermissionKey(s: DescService) {
  if (s.proto.options && hasExtension(s.proto.options, permissionKey)) {
    return getExtension(s.proto.options, permissionKey)
  }
  return ""
}

function getPermissionAbility(m: DescMethod) {
  if (m.proto.options && hasExtension(m.proto.options, permissionAbility)) {
    return getExtension(m.proto.options, permissionAbility)
  }
  return ""
}

function getPermissionAllowAll(m: DescMethod) {
  if (m.proto.options && hasExtension(m.proto.options, permissionAllowAll)) {
    return getExtension(m.proto.options, permissionAllowAll)
  }
  return false
}

runNodeJs(protoGenTSEnums);
