import {createEcmaScriptPlugin, runNodeJs} from "@bufbuild/protoplugin";
import {type Schema} from "@bufbuild/protoplugin/ecmascript";
import {DescMethod, DescService, getExtension, hasExtension} from "@bufbuild/protobuf";
import {permissionAbility, permissionAllowAll, permissionKey} from "../gen/api/v1/permissions_pb";
import {fileIgnored} from "./utils";
import { capitalCase } from 'change-case';

const protoGenTSEnums = createEcmaScriptPlugin({
  name: "permission-plugin",
  version: `v1.0.0`,
  generateTs,
});

function generateTs(schema: Schema) {

  const f = schema.generateFile("permission-autocomplete.ts");

  console.error("Created permission-autocomplete.ts")
  f.print(`// generated by permission-autocomplete-plugin`)
  f.print(`// DO NOT EDIT`)

  f.print("import { IAutocompleteItem } from '@gen/interface';")

  f.print(`export const PermissionAutocompleteItems = [`)

  const items = [];

  const renderService = (s: DescService) => {
    // check if the service has a api.v1.permissionGroup extension

    const key = getPermissionKey(s)
    if (key == "") {
      return
    }

    items.push({
      ID: key,
      label: capitalCase(key),
    })
  }

  for (const file of schema.files) {
    if ([
      "buf/validate/"
    ].some(prefix => file.name.startsWith(prefix))) continue;

    // check if the file is ignored
    if (fileIgnored(file)) {
      continue;
    }

    for (const s of file.services) {
      renderService(s)
    }
  }

  items.forEach(i => {
    f.print(`  ${JSON.stringify(i)},`)
  })

  f.print(`] as IAutocompleteItem[];`)
}

function getPermissionKey(s: DescService) {
  if (s.proto.options && hasExtension(s.proto.options, permissionKey)) {
    return getExtension(s.proto.options, permissionKey)
  }
  return ""
}

runNodeJs(protoGenTSEnums);
