import {createEcmaScriptPlugin, runNodeJs} from "@bufbuild/protoplugin";
import {type Schema} from "@bufbuild/protoplugin/ecmascript";
import {DescMessage} from "@bufbuild/protobuf";
import {enumName, messageName, resolveScalarType} from "./utils";

const protoGenTSEnums = createEcmaScriptPlugin({
    name: "typemap-plugin",
    version: `v1.0.0`,
    generateTs,
});

interface FieldMap {
    [key: string]: Field;
}

interface Field {
    name: string;
    optional: boolean;
    type: string;
    array: boolean;
    custom: boolean;
    jsonb: boolean;
    oneOf: boolean;
}

function generateTs(schema: Schema) {

    const f = schema.generateFile("typemap.ts");
    const debug = false;

    console.error("Created typemap.ts")
    f.print(`// **********
// generated by typemap-plugin
// Do not edit it directly.
// *********
interface Field {
    name: string;
    optional: boolean;
    type: string;
    array: boolean;
    custom: boolean;
    jsonb: boolean;
    oneOf: boolean;
}

interface FieldMap {
    [key: string]: Field;
}
    `)

    const fieldMaps: string[] = []

    const renderMessage = (m: DescMessage) => {

        if(debug) f.print(`// @generated from message ${m.typeName}`)

        const name = `${messageName(m)}FieldMap`;
        const fm: FieldMap = {}

        for( const of of m.oneofs ) {
            const t = of.fields.map((f) => {
                switch (f.fieldKind) {
                    case "scalar":
                        return resolveScalarType(f.scalar)
                    case "message":
                        return messageName(f.message)
                    case "enum":
                        return enumName(f.enum)
                }
            })

            fm[of.name] = {
                name: of.name,
                optional: false,
                type: t.join(" | "),
                array: false,
                custom: true,
                jsonb: false,
                oneOf: true
            };
        }

        for (const field of m.fields) {

            if( field.oneof ) continue;

            const f: Field = {
                name: field.name,
                optional: field.optional,
                type: "unknown",
                array: field.repeated,
                custom: false,
                jsonb: false,
                oneOf: field.oneof !== undefined
            }

            if( field.fieldKind === "message" ) {
                f.custom = true;
                f.type = messageName(field.message)
                f.jsonb = isJsonB(field.message);
            }
            if( field.fieldKind === "enum" ) {
                f.custom = true;
                f.type = enumName(field.enum)
            }
            if ( field.fieldKind === "scalar" ) {
                f.type = resolveScalarType(field.scalar)
            }

            if( field.fieldKind === "map" ) {
                const k = resolveScalarType(field.mapKey!)
                let v = "any"
                switch(field.mapValue.kind) {
                    case "message":
                        v = messageName(field.mapValue.message)
                        break;
                    case "enum":
                        v = enumName(field.mapValue.enum)
                        break;
                    case "scalar":
                        v = resolveScalarType(field.mapValue.scalar)
                        break;
                }
                f.type = `map<${k}, ${v}>`
            }

            fm[field.name] = f;
        }

        f.print(`const ${name}: FieldMap = ${JSON.stringify(fm, null, 4)}`)
        fieldMaps.push(messageName(m))

    }

    const messages = new Map<string, DescMessage>()

    const accumulateMessages = (m: DescMessage) => {
        messages.set(messageName(m), m)
        for (const nm of m.nestedMessages) {
            accumulateMessages(nm)
        }
    }

    for (const file of schema.files) {
        if ([
            "buf/validate/"
        ].some(prefix => file.name.startsWith(prefix))) continue;
        for ( const m of file.messages) {
            accumulateMessages(m)
        }
    }

    messages.forEach((m) => {
        renderMessage(m)
    })

    f.print(`const globals = {`)

    fieldMaps.forEach((name) => {
        f.print(`   ${name}: ${name}FieldMap,`)
    })

    f.print(`}`)
    f.print(`export default globals`)
    f.print(`export type TypeMap = typeof globals;`)

}

const isJsonB = (m: DescMessage) => {
    const c = m.getComments().leading || ""
    return c.match(/@JSON/) !== null
}

runNodeJs(protoGenTSEnums);
