#!/usr/bin/env bash
# Stack registry: per-worktree port allocation + tmux/compose isolation.
#
# Sourced by run-stack.sh, stop-stack.sh, spin-up.sh, list-stacks.sh.
# Persists state under ~/.utro-stacks/<id>/ so multiple worktrees can run
# side-by-side without port clashes.
#
# Public functions (after sourcing):
#   stack_id            — short hash of worktree root
#   stack_dir           — directory under $UTRO_STACKS_HOME
#   stack_session       — tmux session name for this stack
#   stack_compose_proj  — docker compose project name for this stack
#   ensure_registry     — allocate ports & write stack.env if missing; safe to re-run
#   load_registry       — source stack.env into the current shell
#   export_stack_env    — load_registry + export every var so child procs inherit
#   ports_in_registry   — print all *_PORT values from stack.env (one per line)
#
# All output to stdout is meant to be captured; diagnostic logs go to stderr.

# Resolve repo root from the caller's location. Caller must `cd` to repo before
# sourcing, OR pass UTRO_REPO_ROOT explicitly.
: "${UTRO_REPO_ROOT:=$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
: "${UTRO_STACKS_HOME:=$HOME/.utro-stacks}"

stack_id() {
  printf '%s' "$UTRO_REPO_ROOT" | shasum | cut -c1-8
}

stack_dir() {
  printf '%s/%s' "$UTRO_STACKS_HOME" "$(stack_id)"
}

stack_session() {
  printf '__utro-stack-%s__' "$(stack_id)"
}

stack_compose_proj() {
  # Compose project names: lowercase, alnum + hyphen/underscore only.
  printf 'utro-%s' "$(stack_id)"
}

_log() { printf '[stack] %s\n' "$*" >&2; }

# Print a free TCP port, preferring $1 if available.
# Race window is ~ms between probe and actual bind; acceptable for dev.
_alloc_port() {
  local preferred="${1:-}"
  if [ -n "$preferred" ] && ! lsof -nP -iTCP:"$preferred" -sTCP:LISTEN -t >/dev/null 2>&1; then
    printf '%s\n' "$preferred"
    return 0
  fi
  python3 -c 'import socket
s=socket.socket()
s.bind(("127.0.0.1",0))
print(s.getsockname()[1])
s.close()'
}

# Write stack.env atomically with all allocated ports + composed URLs.
# Idempotent: returns early if registry already exists.
ensure_registry() {
  local dir
  dir=$(stack_dir)
  if [ -f "$dir/stack.env" ]; then
    return 0
  fi

  mkdir -p "$dir"
  _log "allocating ports for $(stack_id) ($UTRO_REPO_ROOT)"

  local postgres_port redis_port pgadmin_port \
    gateway_port gateway_health_port core_port core_health_port \
    bootstrap_api_port bootstrap_health_port \
    payment_port payment_health_port notification_port notification_health_port \
    core_event_health_port ui_port

  postgres_port=$(_alloc_port 5432)
  redis_port=$(_alloc_port 6379)
  pgadmin_port=$(_alloc_port 5050)
  gateway_port=$(_alloc_port 9999)
  # Health ports across services share a default of 8081 (pkg/health/config.go).
  # Allocate distinct ports for the two services that use the default
  # (gateway, payment) to avoid both binding 8081 simultaneously.
  gateway_health_port=$(_alloc_port 8081)
  payment_health_port=$(_alloc_port 8082)
  core_port=$(_alloc_port 9102)
  core_health_port=$(_alloc_port 18007)
  bootstrap_api_port=$(_alloc_port 8080)
  bootstrap_health_port=$(_alloc_port 18008)
  payment_port=$(_alloc_port 9001)
  notification_port=$(_alloc_port 9002)
  notification_health_port=$(_alloc_port 18009)
  core_event_health_port=$(_alloc_port 18010)
  ui_port=$(_alloc_port 3000)
  # OTel collector + Grafana (LGTM bundle). One per worktree so parallel
  # stacks don't fight over 4317/4318/3001 or mix telemetry data.
  local otel_grpc_port otel_http_port grafana_port
  otel_grpc_port=$(_alloc_port 4317)
  otel_http_port=$(_alloc_port 4318)
  grafana_port=$(_alloc_port 3001)

  local tmp="$dir/stack.env.tmp"
  cat > "$tmp" <<EOF
# Auto-generated by tools/stack/registry.sh — do not edit by hand.
# Worktree: $UTRO_REPO_ROOT
# Stack ID: $(stack_id)
STACK_ID=$(stack_id)
STACK_WORKTREE=$UTRO_REPO_ROOT
STACK_TMUX_SESSION=$(stack_session)
COMPOSE_PROJECT_NAME=$(stack_compose_proj)

# Infra (host-side ports; container-side stays canonical)
POSTGRES_HOST_PORT=$postgres_port
REDIS_HOST_PORT=$redis_port
PGADMIN_HOST_PORT=$pgadmin_port
OTEL_GRPC_HOST_PORT=$otel_grpc_port
OTEL_HTTP_HOST_PORT=$otel_http_port
GRAFANA_HOST_PORT=$grafana_port

# Service ports
GATEWAY_API_PORT=$gateway_port
GATEWAY_HEALTH_PORT=$gateway_health_port
CORE_API_PORT=$core_port
CORE_HEALTH_PORT=$core_health_port
BOOTSTRAP_API_PORT=$bootstrap_api_port
BOOTSTRAP_HEALTH_PORT=$bootstrap_health_port
PAYMENT_API_PORT=$payment_port
PAYMENT_HEALTH_PORT=$payment_health_port
NOTIFICATION_API_PORT=$notification_port
NOTIFICATION_HEALTH_PORT=$notification_health_port
CORE_EVENT_HEALTH_PORT=$core_event_health_port
UI_PORT=$ui_port

# Cross-references consumed by services (override .env.dev defaults via shell env).
# NOTE: API_PORT and HEALTH_PORT are deliberately NOT set here — those names
# are per-service (gateway's API_PORT != core's), so run-stack.sh injects them
# inline per pane to avoid cross-contamination.
DB_HOST=localhost
DB_PORT=$postgres_port
REDIS_ADDRESS=localhost:$redis_port
CORE_SERVICE=localhost:$core_port
PAYMENT_SERVICE=localhost:$payment_port
PAYMENT_SERVICE_URL=http://localhost:$payment_port
CORE_API_URL=http://localhost:$core_port
NOTIFICATION_SERVICE=localhost:$notification_port
GATEWAY_URL=http://localhost:$gateway_port

# UI runtime env (Next.js — process.env wins over .env.local)
BFF_URL=http://127.0.0.1:$gateway_port
API_URL=http://127.0.0.1:$payment_port
NEXT_PUBLIC_API_URL=http://127.0.0.1:$ui_port/api/rpc
NEXTAUTH_URL=http://localhost:$ui_port

# Telemetry (override .env.dev / .env.local defaults so each stack
# emits to its own LGTM bundle).
TR_ENDPOINT=localhost:$otel_http_port
NEXT_PUBLIC_OTEL_ENDPOINT=http://localhost:$otel_http_port/v1/traces

# Cypress entry points (read by tools/e2e-test/cypress.config.ts and our skill)
CYPRESS_BASE_URL=http://localhost:$ui_port
CYPRESS_BOOTSTRAP_API_URL=http://localhost:$bootstrap_api_port
EOF
  mv "$tmp" "$dir/stack.env"
  printf '%s\n' "$UTRO_REPO_ROOT" > "$dir/worktree"
  _log "registry written: $dir/stack.env"
}

load_registry() {
  local f
  f="$(stack_dir)/stack.env"
  if [ ! -f "$f" ]; then
    _log "no registry at $f — call ensure_registry first" >&2
    return 1
  fi
  # shellcheck disable=SC1090
  . "$f"
}

# Source the registry AND export every var, so child procs (go run, nx,
# docker compose) pick them up without per-call -e / --env.
export_stack_env() {
  load_registry || return 1
  set -a
  # Re-source under set -a to mark all as exported.
  # shellcheck disable=SC1090
  . "$(stack_dir)/stack.env"
  set +a
}

ports_in_registry() {
  local f="$(stack_dir)/stack.env"
  [ -f "$f" ] || return 0
  awk -F= '/_PORT=/ { print $2 }' "$f"
}
