-- +goose Up
ALTER TABLE core.session REPLICA IDENTITY FULL;
ALTER TABLE core.therapist REPLICA IDENTITY FULL;

-- +goose Down
ALTER TABLE core.session REPLICA IDENTITY DEFAULT;
ALTER TABLE core.therapist REPLICA IDENTITY DEFAULT;
